name: crossscp
description: "High-performance cross-platform SFTP client"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  ffi: ^2.2.0
  path_provider: ^2.1.0
  path: ^1.9.0
  uuid: ^4.3.0
  fluent_ui: ^4.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
